# ── Repository ────────────────────────────────────────────────────────────

def init(path: str | None = None) -> str: ...
def open(path: str | None = None) -> str: ...
def status() -> dict: ...
def commit(
    message: str,
    *,
    author: str | None = None,
    force_full: bool = False,
    branch: str | None = None,
    body: str | None = None,
    is_checkpoint: bool = False,
    is_ai: bool = False,
) -> dict: ...
def log(limit: int = 20, branch: str | None = None) -> list[dict]: ...
def rollback(snapshot_id: str, *, reason: str | None = None) -> dict: ...
def changes() -> list[dict]: ...
def diff(from_snapshot: str, to_snapshot: str) -> list[dict]: ...
def undo() -> dict: ...
def redo() -> dict: ...
def history(limit: int = 20) -> list[dict]: ...
def checkpoint(title: str, *, body: str | None = None) -> dict: ...
def stats() -> dict: ...
def all_snapshots() -> list[dict]: ...
def backup(target: str) -> str: ...
def annotate(commit_id: str, text: str) -> dict: ...
def annotations(commit_id: str) -> list[dict]: ...

# ── Branch ────────────────────────────────────────────────────────────────

def branch_list() -> list[dict]: ...
def branch_create(
    name: str,
    *,
    kind: str = "inherited",
    from_branch: str | None = None,
) -> dict: ...
def branch_switch(name: str) -> None: ...
def branch_delete(name: str) -> None: ...

# ── Tag ───────────────────────────────────────────────────────────────────

def tag_list() -> list[dict]: ...
def tag_create(name: str, *, message: str | None = None) -> dict: ...
def tag_delete(name: str) -> None: ...

# ── Conversation ──────────────────────────────────────────────────────────

def conversation_new(title: str) -> str: ...
def conversation_list() -> list[dict]: ...
def conversation_show(session_id: str, *, limit: int | None = None) -> dict: ...
def conversation_record(
    session_id: str,
    role: str,
    content: str,
    *,
    snapshot_id: str | None = None,
) -> dict: ...
def conversation_rollback(
    session_id: str,
    message_id: str,
    *,
    reason: str | None = None,
) -> dict: ...
def conversation_archive(session_id: str) -> None: ...
def conversation_delete(session_id: str) -> None: ...