//! Example data seeder — produces a realistic, fully-populated sample
//! project so the user can see the entire feature surface in one view.
//!
//! Used by the "Try example project" button on the welcome page. Creates
//! a directory under `target_dir`, writes a small, plausible source tree,
//! then runs a curated sequence of operations:
//!
//!   1.  Initialize a basic-mode repo at the project root.
//!   2.  Several user commits on `main` (incremental, normal cadence).
//!   3.  One user checkpoint at the half-way point.
//!   4.  An AI-driven commit with operator="ai:claude" + prompt body.
//!   5.  Another user commit, then an undo (rollback).
//!   6.  A sandbox branch + a couple of changes on it.
//!   7.  An inherited branch + a couple of changes on it.
//!   8.  A redo on main to show the chain recovering.
//!   9.  A second AI commit, this time introducing a "conflicted file".
//!
//! Every commit is real (no synthetic timestamps) — the seeder sleeps a
//! few milliseconds between calls so the file-watcher / diff-summary
//! pipeline has time to see each write. The result is a project the
//! frontend can render with full branches, checkpoints, AI operators,
//! rollbacks, and a multi-branch history.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::thread::sleep;
use std::time::Duration;

use anyhow::Result;
use route_basic::{
    BasicRepository, BranchKind, CommitOptions, CreateBranchOptions,
};

use crate::state::AppState;

/// Built-in name for the seeded project. Used to surface the path in the
/// UI after creation.
pub const EXAMPLE_PROJECT_NAME: &str = "route-example (sample)";

/// Layout of the demo source tree. The contents are intentionally
/// realistic-looking — small, plausible Python + Markdown + JSON.
mod files {
    pub const README: &str = r#"---
title: route-example
---

A tiny example project used to demonstrate route's full feature set.

This project is auto-generated by the "Try example project" button on
the welcome page. Delete the directory to remove it.
"#;

    pub const APP_PY_V1: &str = r#"# route_example/app.py
# A minimal Flask-style app. Real-world projects would split this into
# multiple modules; we keep it in one file so the history is readable.

from flask import Flask, jsonify, request


def create_app() -> Flask:
    app = Flask(__name__)

    @app.get("/health")
    def health():
        return jsonify(status="ok")

    @app.get("/sum")
    def sum_():
        a = float(request.args.get("a", "0"))
        b = float(request.args.get("b", "0"))
        return jsonify(result=a + b)

    return app


if __name__ == "__main__":
    create_app().run(debug=True)
"#;

    pub const APP_PY_V2: &str = r#"# route_example/app.py
# v2: validates inputs, returns 400 on bad params, and supports /mul.

from flask import Flask, jsonify, request


def create_app() -> Flask:
    app = Flask(__name__)

    @app.get("/health")
    def health():
        return jsonify(status="ok")

    def _floats() -> tuple[float, float] | tuple[None, None]:
        try:
            return float(request.args["a"]), float(request.args["b"])
        except (KeyError, ValueError):
            return None, None

    @app.get("/sum")
    def sum_():
        a, b = _floats()
        if a is None:
            return jsonify(error="bad params"), 400
        return jsonify(result=a + b)

    @app.get("/mul")
    def mul():
        a, b = _floats()
        if a is None:
            return jsonify(error="bad params"), 400
        return jsonify(result=a * b)

    return app


if __name__ == "__main__":
    create_app().run(debug=True)
"#;

    pub const TESTS_PY_V1: &str = r#"# route_example/tests.py
# Smoke tests. We don't pull in pytest — these are runnable with
# `python tests.py` so the project is self-contained.

from app import create_app


def test_health():
    c = create_app().test_client()
    r = c.get("/health")
    assert r.status_code == 200
    assert r.get_json() == {"status": "ok"}


def test_sum():
    c = create_app().test_client()
    r = c.get("/sum?a=2&b=3")
    assert r.status_code == 200
    assert r.get_json() == {"result": 5.0}


if __name__ == "__main__":
    test_health()
    test_sum()
    print("ok")
"#;

    pub const TESTS_PY_V2: &str = r#"# route_example/tests.py
# v2: covers /mul and the new 400 path.

from app import create_app


def test_health():
    c = create_app().test_client()
    r = c.get("/health")
    assert r.status_code == 200
    assert r.get_json() == {"status": "ok"}


def test_sum_ok():
    c = create_app().test_client()
    r = c.get("/sum?a=2&b=3")
    assert r.status_code == 200
    assert r.get_json() == {"result": 5.0}


def test_sum_bad():
    c = create_app().test_client()
    r = c.get("/sum?a=x&b=3")
    assert r.status_code == 400


def test_mul():
    c = create_app().test_client()
    r = c.get("/mul?a=4&b=5")
    assert r.status_code == 200
    assert r.get_json() == {"result": 20.0}


if __name__ == "__main__":
    for fn in (test_health, test_sum_ok, test_sum_bad, test_mul):
        fn()
    print("ok")
"#;

    pub const CONFIG_JSON: &str = r#"{
  "name": "route-example",
  "version": "0.1.0",
  "description": "Sample project for route's example seed."
}
"#;

    pub const NOTES_MD_V1: &str = "# notes\n\n- Initial scaffold.\n";
    pub const NOTES_MD_V2: &str = "# notes\n\n- Initial scaffold.\n- Added /mul endpoint.\n- Validated input handling.\n";
    pub const NOTES_MD_V3: &str = "# notes\n\n- Initial scaffold.\n- Added /mul endpoint.\n- Validated input handling.\n- AI: refactored /sum to share parser with /mul.\n";

    pub const AI_REFACTOR_PY: &str = r#"# route_example/ai_refactor.py
# Generated by ai:claude — extracted the float parser into a helper.

from app import create_app


def helper(a: str, b: str):
    try:
        return float(a) + float(b)
    except ValueError:
        return None


if __name__ == "__main__":
    print(helper("2", "3"))
"#;

    pub const SANDBOX_TXT: &str = "scratch notes — only on the sandbox branch, will not be merged\n";

    pub const INHERITED_TXT: &str = "experimental: trying a new routing approach\n";
}

/// Write `text` to `path`, creating parent directories. Atomic enough
/// for the seeder's purposes (the watcher will pick it up after a short
/// delay).
fn write_text(path: &Path, text: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut f = fs::File::create(path)?;
    f.write_all(text.as_bytes())?;
    f.sync_all()?;
    Ok(())
}

/// Sleep long enough that any per-write notifications settle before
/// the next commit runs. Without this, two writes in the same millisecond
/// may collapse into a single commit.
fn beat() {
    sleep(Duration::from_millis(40));
}

/// Seed a complete example project at `project_path`. If the directory
/// already exists with a `.route-basic/` inside, it is reused
/// (idempotent). The created repo is NOT set as the global active
/// repo — the caller (`seed_example_command`) does that after this
/// returns.
pub fn seed_example(project_path: &Path) -> Result<BasicRepository> {
    if project_path.exists() {
        // If a previous seed left a real route repo, just open it. This
        // makes the "Try example" button safe to click twice. Note:
        // basic-mode uses `.route-basic/`, NOT `.route/` (the latter is
        // reserved for AI-facing config like `index.json`). Checking the
        // wrong directory would cause this branch to fall through to
        // `remove_dir_all`, which would then re-seed on top of an
        // existing database and trip the UNIQUE constraint on
        // `branches.name`.
        if project_path.join(".route-basic").exists() {
            return BasicRepository::open(project_path).map(|r| r.with_serial_scanner());
        }
        // Stale dir without a repo — wipe and re-seed.
        let _ = fs::remove_dir_all(project_path);
    }
    fs::create_dir_all(project_path)?;

    // --- 1. Drop initial source tree. ---
    let root = project_path.to_path_buf();
    write_text(&root.join("README.md"), files::README)?;
    write_text(&root.join("config.json"), files::CONFIG_JSON)?;
    write_text(&root.join("app.py"), files::APP_PY_V1)?;
    write_text(&root.join("tests.py"), files::TESTS_PY_V1)?;
    write_text(&root.join("notes.md"), files::NOTES_MD_V1)?;
    beat();

    // --- 2. Initialize. ---
    let repo = BasicRepository::init(project_path)?.with_serial_scanner();
    repo.commit(CommitOptions {
        message: "Initial scaffold (README, app.py, tests.py, config.json)".into(),
        ..Default::default()
    })?;
    beat();

    // --- 3. Checkpoint #1 — the "v0.1" marker. ---
    repo.checkpoint_create(
        "v0.1 — initial scaffold",
        Some("First end-to-end smoke tests pass. Pinning the baseline before further work."),
        Some("user"),
    )?;
    beat();

    // --- 4. Edit app.py: input validation + new /mul endpoint. ---
    write_text(&root.join("app.py"), files::APP_PY_V2)?;
    beat();
    repo.commit(CommitOptions {
        message: "app.py: validate params, add /mul".into(),
        ..Default::default()
    })?;
    beat();

    // --- 5. AI commit — extract float parser into helper. ---
    write_text(&root.join("ai_refactor.py"), files::AI_REFACTOR_PY)?;
    beat();
    repo.commit(CommitOptions {
        message: "AI: extract float parser helper".into(),
        operator: Some("ai:claude".into()),
        body: Some(
            "Refactor the duplicated float-parsing logic in /sum and /mul into a single helper \
             to remove the copy-paste and centralize error handling. Keep the public API identical."
                .into(),
        ),
        is_ai: true,
        ..Default::default()
    })?;
    beat();

    // --- 6. Update tests + notes (user). ---
    write_text(&root.join("tests.py"), files::TESTS_PY_V2)?;
    write_text(&root.join("notes.md"), files::NOTES_MD_V2)?;
    beat();
    repo.commit(CommitOptions {
        message: "tests: cover /mul and 400 path; update notes".into(),
        ..Default::default()
    })?;
    beat();

    // --- 7. Checkpoint #2 — "v0.2" marker. ---
    repo.checkpoint_create(
        "v0.2 — feature complete",
        Some("All endpoints implemented, tests green, ready for review."),
        Some("user"),
    )?;
    beat();

    // --- 8. Sandbox branch — fully independent, never merged. ---
    let _ = repo.create_branch(
        "sandbox/experiments",
        CreateBranchOptions {
            kind: BranchKind::Sandbox,
            from_branch: Some("main".into()),
        },
        "main",
    );
    repo.set_current_branch("sandbox/experiments")?;
    write_text(&root.join("sandbox-notes.txt"), files::SANDBOX_TXT)?;
    beat();
    repo.commit(CommitOptions {
        message: "sandbox: add scratch notes (won't be merged)".into(),
        ..Default::default()
    })?;
    beat();

    // --- 9. Inherited branch — shares main's baseline. ---
    repo.set_current_branch("main")?;
    let _ = repo.create_branch(
        "feature/routing",
        CreateBranchOptions {
            kind: BranchKind::Inherited,
            from_branch: Some("main".into()),
        },
        "main",
    );
    repo.set_current_branch("feature/routing")?;
    write_text(&root.join("experimental-routing.txt"), files::INHERITED_TXT)?;
    beat();
    repo.commit(CommitOptions {
        message: "feature/routing: experiment with new dispatcher".into(),
        ..Default::default()
    })?;
    beat();
    write_text(&root.join("notes.md"), files::NOTES_MD_V3)?;
    beat();
    repo.commit(CommitOptions {
        message: "feature/routing: align notes with new direction".into(),
        ..Default::default()
    })?;

    // --- 10. Back to main, undo the AI commit to show the rollback chain. ---
    repo.set_current_branch("main")?;
    let _undo = repo.undo_last()?;
    beat();

    // --- 11. Redo it. ---
    let _redo = repo.redo_last()?;
    beat();

    Ok(repo)
}

/// Run `f` on a fresh thread with a 64 MB stack. The default Windows
/// thread stack is 1 MB, which trips STATUS_STACK_OVERFLOW on the deep
/// rusqlite + Tauri + tokio call chains that `seed_example` exercises
/// (initial commit, several user commits, AI commit, branches, undo,
/// redo — all in one go). Tauri commands run on tokio workers which
/// inherit the same 1 MB limit, so without this helper, clicking the
/// "Try example project" button on a fresh install kills the whole
/// process. (The previous, more serious stack overflow inside the
/// seeder was caused by an infinite-recursion bug in
/// `resolve_snapshot_files` — fixed separately; the big-stack thread
/// is still a useful safety net for the other Tauri-internal calls
/// in the seeder.)
fn run_on_big_stack<F, R>(f: F) -> Result<R, String>
where
    F: FnOnce() -> Result<R, String> + Send + 'static,
    R: Send + 'static,
{
    let join = std::thread::Builder::new()
        .name("route-seed-bigstack".into())
        .stack_size(64 * 1024 * 1024)
        .spawn(f)
        .map_err(|e| format!("failed to spawn big-stack thread: {e}"))?
        .join();
    match join {
        Ok(inner) => inner,
        Err(_) => Err("seed thread panicked".to_string()),
    }
}

/// Build an example project at `target_dir/example/` on a big-stack
/// thread and return the resulting `(BasicRepository, project_path)`.
/// Splitting this out from `seed_example_command` lets the Tauri
/// command do the small-stack `state.set_repo(...)` itself, instead
/// of trying to move the `&AppState` into the spawned thread.
pub fn seed_example_on_big_stack(
    target_dir: String,
) -> Result<(BasicRepository, PathBuf), String> {
    run_on_big_stack(move || -> Result<(BasicRepository, PathBuf), String> {
        let target = PathBuf::from(&target_dir);
        fs::create_dir_all(&target).map_err(|e| e.to_string())?;
        let project_path = target.join(EXAMPLE_PROJECT_NAME);
        let project_path_for_repo = project_path.clone();
        let repo = seed_example(&project_path_for_repo).map_err(|e| e.to_string())?;
        Ok((repo, project_path))
    })
}

/// Tauri command: seed an example project at `target_dir/example/`
/// (creating the directory if missing), set it as the active repo, and
/// return the resulting `StatusDto`. Mirrors `init_repo` so the frontend
/// can drop the response in its existing state.
pub fn seed_example_command(
    target_dir: String,
    state: &AppState,
) -> Result<crate::commands::StatusDto, String> {
    tracing::info!(target_dir = %target_dir, "seed_example_command: starting");
    // Build the repo on a 64 MB stack. Tauri command handlers run on
    // tokio workers with the platform-default 1 MB stack on Windows,
    // which is too tight for `seed_example` — it does many commits +
    // branch operations back to back, and the deep rusqlite + tokio +
    // Tauri-internals stack chains push past 1 MB. Spawning a fresh
    // thread with a much larger stack fixes the crash.
    let (repo, project_path) = match seed_example_on_big_stack(target_dir) {
        Ok(v) => {
            tracing::info!(path = %v.1.display(), "seed_example_on_big_stack: ok");
            v
        }
        Err(e) => {
            tracing::error!(error = %e, "seed_example_on_big_stack: failed");
            return Err(e);
        }
    };
    let dto = match crate::commands::build_status(&repo) {
        Ok(d) => d,
        Err(e) => {
            tracing::error!(error = %e, "build_status: failed");
            return Err(e.to_string());
        }
    };
    state.set_repo(repo);
    if let Ok(mut p) = state.project_path.lock() {
        *p = Some(project_path);
    }
    tracing::info!("seed_example_command: completed");
    Ok(dto)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::thread;
    use tempfile::TempDir;

    /// Run `f` on a fresh thread with a 32 MB stack. The default
    /// Windows test thread is 1 MB, which trips STATUS_STACK_OVERFLOW
    /// in the deep Tauri + rusqlite + tokio call chains during
    /// commit / branch / undo operations.
    fn on_big_stack<F: FnOnce() + Send + 'static>(f: F) {
        thread::Builder::new()
            .stack_size(32 * 1024 * 1024)
            .spawn(f)
            .expect("spawn big-stack thread")
            .join()
            .expect("big-stack thread should not panic")
    }

    /// Smoke: the seeder produces a repo with three branches, at least
    /// one AI commit, and at least one checkpoint.
    #[test]
    fn seed_produces_full_feature_set() {
        on_big_stack(|| {
            let tmp = TempDir::new().unwrap();
            let project = tmp.path().join("example");

            let repo = seed_example(&project).expect("seed_example should succeed");

            // Branches: main + sandbox + at least one inherited.
            let branches = repo.list_branches().expect("list_branches");
            let names: Vec<&str> = branches.iter().map(|b| b.name.as_str()).collect();
            assert!(names.contains(&"main"), "main branch must exist");
            assert!(
                names.iter().any(|n| n.starts_with("sandbox/")),
                "at least one sandbox branch must exist; got: {:?}",
                names
            );
            assert!(
                names.iter().any(|n| n.starts_with("feature/") || n.starts_with("feat/")),
                "at least one inherited branch must exist; got: {:?}",
                names
            );

            // Commits: at least one AI commit, at least one checkpoint.
            let all = repo.list_commits(None, 200).expect("list_commits");
            let ai_count = all.iter().filter(|c| c.is_ai).count();
            let cp_count = all.iter().filter(|c| c.is_checkpoint).count();
            assert!(ai_count >= 1, "expected at least one AI commit, found {ai_count}");
            assert!(cp_count >= 1, "expected at least one checkpoint, found {cp_count}");

            // Sandbox branch must exist with kind=Sandbox.
            let sandbox = branches
                .iter()
                .find(|b| b.name.starts_with("sandbox/"))
                .expect("sandbox branch must exist");
            assert_eq!(sandbox.kind, route_basic::BranchKind::Sandbox);

            // Inherited branch must be kind=Inherited.
            let inherited = branches
                .iter()
                .find(|b| {
                    b.kind == route_basic::BranchKind::Inherited
                        && (b.name.starts_with("feature/") || b.name.starts_with("feat/"))
                })
                .expect("inherited branch must exist");
            assert_eq!(inherited.kind, route_basic::BranchKind::Inherited);

            // Re-opening the seeded directory must succeed (idempotent).
            let reopened = seed_example(&project).expect("reopen should succeed");
            let again = reopened.list_branches().expect("branches after reopen");
            assert_eq!(
                again.len(),
                branches.len(),
                "re-opening should not duplicate branches"
            );
        });
    }

    /// The seeder must drop a real source tree on disk so the user
    /// can see the resulting files. We don't diff the contents — just
    /// assert that the expected top-level files exist.
    #[test]
    fn seed_writes_expected_files() {
        on_big_stack(|| {
            let tmp = TempDir::new().unwrap();
            let project = tmp.path().join("example");
            let _ = seed_example(&project).unwrap();

            for rel in ["README.md", "app.py", "tests.py", "config.json", "notes.md"] {
                assert!(
                    project.join(rel).exists(),
                    "expected file {} to exist on disk",
                    rel
                );
            }
        });
    }
}
